@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --onefile --windowed --icon "F:\SteamAutoCracker\icon_hashtag.ico" --name "steam_auto_cracker_gui" --add-data "F:\SteamAutoCracker\sac_lib;sac_lib/"  "F:\SteamAutoCracker\steam_auto_cracker_gui.py"
pause
